package model.hibernate.pojo;
// Generated Jun 1, 2018 5:38:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Administrator generated by hbm2java
 */
public class Administrator  implements java.io.Serializable {


     private Integer administratorId;
     private Employee employee;
     private Set<Performance> performances = new HashSet<Performance>(0);
     private Adminaccount adminaccount;

    public Administrator() {
    }

	
    public Administrator(Employee employee) {
        this.employee = employee;
    }
    public Administrator(Employee employee, Set<Performance> performances, Adminaccount adminaccount) {
       this.employee = employee;
       this.performances = performances;
       this.adminaccount = adminaccount;
    }
   
    public Integer getAdministratorId() {
        return this.administratorId;
    }
    
    public void setAdministratorId(Integer administratorId) {
        this.administratorId = administratorId;
    }
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }
    public Set<Performance> getPerformances() {
        return this.performances;
    }
    
    public void setPerformances(Set<Performance> performances) {
        this.performances = performances;
    }
    public Adminaccount getAdminaccount() {
        return this.adminaccount;
    }
    
    public void setAdminaccount(Adminaccount adminaccount) {
        this.adminaccount = adminaccount;
    }




}


