package model.hibernate.pojo;
// Generated Jun 1, 2018 5:38:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private Integer branchId;
     private Province province;
     private String branchName;
     private String branchAddress;
     private String branchHotLine;
     private String branchEmail;
     private Set<Employee> employees = new HashSet<Employee>(0);

    public Branch() {
    }

	
    public Branch(Province province, String branchName, String branchAddress, String branchHotLine, String branchEmail) {
        this.province = province;
        this.branchName = branchName;
        this.branchAddress = branchAddress;
        this.branchHotLine = branchHotLine;
        this.branchEmail = branchEmail;
    }
    public Branch(Province province, String branchName, String branchAddress, String branchHotLine, String branchEmail, Set<Employee> employees) {
       this.province = province;
       this.branchName = branchName;
       this.branchAddress = branchAddress;
       this.branchHotLine = branchHotLine;
       this.branchEmail = branchEmail;
       this.employees = employees;
    }
   
    public Integer getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(Integer branchId) {
        this.branchId = branchId;
    }
    public Province getProvince() {
        return this.province;
    }
    
    public void setProvince(Province province) {
        this.province = province;
    }
    public String getBranchName() {
        return this.branchName;
    }
    
    public void setBranchName(String branchName) {
        this.branchName = branchName;
    }
    public String getBranchAddress() {
        return this.branchAddress;
    }
    
    public void setBranchAddress(String branchAddress) {
        this.branchAddress = branchAddress;
    }
    public String getBranchHotLine() {
        return this.branchHotLine;
    }
    
    public void setBranchHotLine(String branchHotLine) {
        this.branchHotLine = branchHotLine;
    }
    public String getBranchEmail() {
        return this.branchEmail;
    }
    
    public void setBranchEmail(String branchEmail) {
        this.branchEmail = branchEmail;
    }
    public Set<Employee> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<Employee> employees) {
        this.employees = employees;
    }




}


