package model.hibernate.pojo;
// Generated Jun 1, 2018 5:38:26 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Province generated by hbm2java
 */
public class Province  implements java.io.Serializable {


     private Integer provinceId;
     private String provinceName;
     private String provincePostalCode;
     private Set<Branch> branches = new HashSet<Branch>(0);

    public Province() {
    }

	
    public Province(String provinceName, String provincePostalCode) {
        this.provinceName = provinceName;
        this.provincePostalCode = provincePostalCode;
    }
    public Province(String provinceName, String provincePostalCode, Set<Branch> branches) {
       this.provinceName = provinceName;
       this.provincePostalCode = provincePostalCode;
       this.branches = branches;
    }
   
    public Integer getProvinceId() {
        return this.provinceId;
    }
    
    public void setProvinceId(Integer provinceId) {
        this.provinceId = provinceId;
    }
    public String getProvinceName() {
        return this.provinceName;
    }
    
    public void setProvinceName(String provinceName) {
        this.provinceName = provinceName;
    }
    public String getProvincePostalCode() {
        return this.provincePostalCode;
    }
    
    public void setProvincePostalCode(String provincePostalCode) {
        this.provincePostalCode = provincePostalCode;
    }
    public Set<Branch> getBranches() {
        return this.branches;
    }
    
    public void setBranches(Set<Branch> branches) {
        this.branches = branches;
    }




}


